MINI2/boardapp/urls.py
from django.urls import path, include
from boardapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'boardapp'

urlpatterns = [
    # 자유게시판
    path('freeboard/', views.freeboard, name='freeboard'),
    # 동아리/스터디
    path('studyboard/', views.studyboard, name='studyboard'),
    # 취업/진로
    path('jobboard/', views.jobboard, name='jobboard'),
    # 물물교환/무료나눔
    path('tradeboard/', views.tradeboard, name='tradeboard'),
    path('writetext/', views.writetext, name='writetext'),
    path('<int:pk>/', views.content_view, name='content_view'),
    path('<int:pk>/content_delete/', views.content_delete, name='content_delete'),
    path('comment_write/<int:pk>/', views.comment_write, name='comment_write'),
    path('likes/', views.likes, name="likes"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/calcapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'calcapp'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('donation/', views.donation, name='donation'),
    # 공지사항
    path('notice/', views.notice, name='notice'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('update/<int:blog_id>/', views.update, name='update'),
    path('delete/<int:blog_id>/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('faq/', views.faq, name='faq'),
    path('suggest/', views.suggest, name='suggest'),
    path('qna/', views.qna, name='qna'),

    # 계산기
    path('calcpage/', views.calcpage, name="calcpage"),
    path('calcpage_result/', views.calcpage_result, name="calcpage_result"),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# calcapp/calcpage/

MINI2/config/urls.py
from django.contrib import admin
from django.urls import path, include
import calcapp.views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/', include('mainpage.urls')),
    path('boardapp/', include('boardapp.urls')),
    path('calcapp/', include('calcapp.urls')),
    path('member/', include('member.urls')),
    path('restaurant/', include('restaurant.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/member/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'member'

urlpatterns = [
    path('login/', views.login, name='login'),  
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

    ### 추가된부분 ###
    # 프로필
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/restaurant/urls.py
from django.contrib import admin
from django.urls import path
from restaurant import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.restaurant, name='rest'),
    path('restaurant_list/', views.restaurant_list, name='list'),
    path('<int:pk>/', views.restaurant_detail, name='detail'),
    path('restaurant_review/<int:pk>/', views.restaurant_review, name='review'),
    path('restaurant_search/', views.restaurant_search, name='serach')
    # path('restaurant_search/', views.restaurant_search),
]

MINI2/boardapp/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from member.models import Member
from django.conf import settings

#  모든 자유게시판 게시물 db
class BoardAllContentList(models.Model):
    title = models.CharField(max_length=100)
    # user = models.ForeignKey(Member, on_delete=models.CASCADE) # main user db랑 연결 해야함
    user = models.CharField(max_length=20) # main user db랑 연결 해야함
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    seenum = models.PositiveIntegerField(default=0)
    like = models.ManyToManyField(Member, default=0,related_name='likes') # 좋아요
    # like_count = models.PositiveIntegerField(default=0)
    board_kind = models.CharField(max_length=20)

    def __str__(self):
        return self.title

# # 게시물 별 이미지 db
class Image(models.Model):
    content = models.ForeignKey(BoardAllContentList, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


# 모든 자유게시판 댓글 db
class Board_comment(models.Model):
    content = models.ForeignKey(BoardAllContentList, on_delete=models.CASCADE, null=True, related_name='content')
    comment_date = models.DateTimeField(auto_now_add=True)
    # comment_writer = models.ForeignKey(Member,on_delete=models.CASCADE, null=True)
    comment_writer = models.CharField(max_length=20)
    comment_content = models.TextField(null=True)
    # comment_board_kind = models.CharField(max_length=20)

    def __str__(self):
        return self.title

MINI2/calcapp/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import Blog

class BlogUpdate(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','body', 'images']


# form 이용시 views.py 수정

# from .models import AttendHistroy
# class AttendHistroyFrom(forms.ModelForm):
#     class Meta:
#         model = AttendHistroy
#         fields = '__all__'

MINI2/boardapp/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from .models import BoardAllContentList, Board_comment, Member
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
import json
from django.views.generic import View, ListView, DetailView, FormView, CreateView

# 자유게시판 메인 목록
def freeboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='자유게시판').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################
    context = {
        'list':content_list,
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }
    return render(request, 'boardapp/board_free.html', context)

# 동아리/스터디 메인 목록
def studyboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='동아리/스터디').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }

    return render(request, 'boardapp/board_study.html', context)

# 취업/진로 메인 목록
def jobboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='취업/진로').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }

    return render(request, 'boardapp/board_job.html', context)

# 물물교환/무료나눔 메인 목록
def tradeboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='물물교환/무료나눔').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }
    return render(request, 'boardapp/board_trade.html', context)


# 글쓰기 양식
def writetext(request):
    content = BoardAllContentList()
    # 세션에 로그인 관련 정보 저장
    # 해인
    session_value = request.session['user_name']

    if request.method == 'POST': # 내용 입력후, 전달 할때
        content.title = request.POST['title']
        content.text = request.POST['text']
        content.date = timezone.datetime.now()
        content.user = session_value
        content.board_kind = request.POST['board_kind']
        content.save()

        '''
        for img in request.FILES.getlist('images'):
            # image 객체 생성
            image = Image()
            # 현재 게시물의 기본키 참조
            image.content = content.id
            # images로부터 가져온 이미지파일 하나씩 저장
            image.image = img
            # db에 저장
            image.save()
        '''

        return redirect('/boardapp/' + str(content.pk))
    # 내용 입력 없을 떄
    return render(request, 'boardapp/board_write.html',{})


# 게시글 페이지
def content_view(request, pk):
    content = BoardAllContentList.objects.get(pk=pk)
    content.seenum += 1 # 조회수
    content.save()
    user = Member.objects.all()
    return render(request, 'boardapp/content_view.html', {'content':content})


# 게시글 삭제
def content_delete(request, pk):
    # login_session = request.session.get('login_session','')
    session_user = request.session['user_name']
    print(session_user)
    content = get_object_or_404(BoardAllContentList, pk=pk)
    if content.user == session_user:
        content.delete()
        return redirect('/boardapp/freeboard')
    else:
        return redirect('/boardapp/' + str(content.pk))


# 게시글 댓글
def comment_write(request, pk):
    content = get_object_or_404(BoardAllContentList, pk = pk)
    session_value = request.session['user_name']

    content.content.create(comment_content = request.POST.get('comment'), comment_date = timezone.now(), comment_writer=session_value)
    return redirect('/boardapp/'+str(content.pk))


# 게시글 좋아요
def likes(request):
    # 현재 로그인한 유저
    user = Member.objects.get(user_phone=request.session['user_phone'])

    if request.is_ajax():
        content_id = request.GET['content_id'] # 좋아요 누른 게시물 id
        content = BoardAllContentList.objects.get(id=content_id)
        # print(id)
        like_user_list = content.like.all() # 좋아요 누른 유저 리스트
        print('리스트',like_user_list)

        # 현재 게시물에 좋아요한 사람 중 로그인한사람이 있으면 (이미 좋아요 누른경우이면)
        if user in like_user_list:
            content.like.remove(user) # 현재 로그인한 사람지워
            message ='좋아요취소'
        else:
            content.like.add(user)
            message ='좋아요'

        like_count = content.like.count() # 게시물이 받은 좋아요수
        context={'like_count':like_count, 'message':message}

    return HttpResponse(json.dumps(context), content_type='application/json')

MINI2/mainpage/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from calcapp.models import Blog
from restaurant.models import Rest
from boardapp.models import BoardAllContentList

# Create your views here.
def mainhome(request):
    get_user_phone = request.session.get('user_phone')
    # get_user_phone = request.session['user_phone']
    blogs = Blog.objects.all()
    rest = Rest.objects.all()

    boards = BoardAllContentList.objects.all()

    context = {
        'get_user_phone':get_user_phone,
        'blogs': blogs,
        'rest':rest,
        'boards':boards,
    }

    return render(request, 'mainpage/mainhome.html', context)

MINI2/member/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils import timezone
from django.contrib import messages

from .models import Member
# redierct - url을 이동. name으로 접근. render처럼 context값을 넘기지는 못함.
# render - 화면에 html파일을 띄우기때문에 url이안변함. context값 넘길 수 있음.
# reverse - 

# Create your views here.
def register(request):
    if request.method == 'GET':
        return render(request, 'member/register.html')
     #"POST"
    else: 
        # HTML로부터 받은 정보 확인
        user_name = request.POST['user_name']
        user_pw = request.POST['user_pw']
        user_pwchk = request.POST['user_pwchk']
        user_phone = request.POST['user_phone']

        message_dict = {} # html에 던져줄 dictionary
        
        m = Member(
            user_name = user_name, user_pw=user_pw,
            user_phone = user_phone)
        m.c_date = timezone.now()
        m.save()
        messages.warning(request, '회원가입 성공')
        return redirect('member:register') # urls.py/view-name을 적어야함

def login(request):
    if request.method == 'GET':
        return render(request, 'member/register.html', {})
     # POST
    else:
        # 받은 정보 확인
        u_id = request.POST['user_phone']
        u_pw = request.POST['user_pw']
        
        try:
            m = Member.objects.get(user_phone=u_id)
        
        except:
            return HttpResponse('등록된 회원이 없습니다.')
        else:
            if m.user_pw != u_pw:
                error_messages = '로그인 실패'   
                return render(request, 'member/register.html', 
                        {'error_messages':error_messages})
            else:
                error_messages = ''
                request.session['user_phone'] = u_id
                request.session['user_name'] = m.user_name
                return redirect('mainpage:mainhome')

def logout(request):
    if request.session['user_phone']:
        del request.session['user_phone']
        del request.session['user_name']
        return redirect('mainpage:mainhome')

MINI2/templates/restaurant/restaurant_detail.html
{% extends 'mainpage/mainpage.html' %}


{% block content %}
{% load split %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/restaurant.css">

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js'></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'></script> 
<script defer src='/static/js/restaurant.js'></script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=8deb5ae77ef38486d8a2541c58a9a934&libraries=services"></script>


    <section class="breadcrumb-option spad set-bg" data-setbg="/static/img/submain-bg.png">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>맛집 게시판</h2>
                        <div class="breadcrumb__links">
                            <a href="/restaurant/">추천맛집리스트</a>
                            <a href="/restaurant/restaurant_list">맛집리스트</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- MIDDLE-BOX START -->
    <section class="breadcrumb-option spad set-bg" data-setbg="img/breadcrumb-bg.jpg">
        <div class="container">
            <div class="row">
                <!-- 실제 페이지 내용 쓰기 START-->
                <!-- 검색창 시작 -->
                {% include 'restaurant/restaurant_search.html' %}
                <!-- 검색창 끝-->
                <br>
                <br>
                <div class="container">
                    <div class="row">
                        <div class="col-xs-11 col-md-10 col-centered">

                            <div id="carousel1" class="carousel slide" data-ride="carousel" data-type="multi"
                                data-interval="2500">
                                <div class="carousel-inner">



                                    <div class="item active">
                                        <div class="carousel-col">
                                            <img src="{{ rest.rest_img1 | default:'/static/img/dogie.jpg'}}" class="block">
                                        </div>
                                    </div>
                                    {% if rest.rest_img2 %}
                                    {% for i in rest.rest_img2|split:"@@" %}
                                    <div class="item">
                                        <div class="carousel-col">
                                            <img src="{{ i }}" class="block">
                                        </div>
                                    </div>                      
                                    {% endfor %}
                                    {% endif %}

                                </div>

                                <!-- Controls -->
                                <div class="left carousel-control">
                                    <a href="#carousel1" role="button" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </div>
                                <div class="right carousel-control">
                                    <a href="#carousel1" role="button" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <section class="breadcrumb-option spad set-bg" data-setbg="img/breadcrumb-bg.jpg">
                    <div class="testimonial__item">
                        <h1>{{ rest.rest_name }}</h1>
                        <div class="rating">
                            <h3>{{ rest.rest_score }}</h3>
                            {% for x in rest.rest_starscore %}
                                <i class="fa fa-star"></i>
                            {% endfor %}
                        </div>
                        <br>
                        <br>
                        <div>가게 주소 : {{ rest.rest_address }}</div>
                        <div>음식 종류 : {{ rest.rest_kind }}</div>
                        <div>가격대 : {{rest.rest_price}}</div>
                        <div>가게 전화번호 : {{rest.rest_tel}}</div>
                    </div>
                    <br>
                    <br>

                    <div id="map" style="width:500px;height:400px;"></div>
                    <script>
                        var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
                            mapOption = {
                                center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
                                level: 3 // 지도의 확대 레벨
                            };  

                        // 지도를 생성합니다    
                        var map = new kakao.maps.Map(mapContainer, mapOption); 

                        // 주소-좌표 변환 객체를 생성합니다
                        var geocoder = new kakao.maps.services.Geocoder();

                        // 주소로 좌표를 검색합니다
                        geocoder.addressSearch('{{ rest.rest_address }}', function(result, status) {

                            // 정상적으로 검색이 완료됐으면 
                            if (status === kakao.maps.services.Status.OK) {

                                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                                // 결과값으로 받은 위치를 마커로 표시합니다
                                var marker = new kakao.maps.Marker({
                                    map: map,
                                    position: coords
                                });

                                // 인포윈도우로 장소에 대한 설명을 표시합니다
                                var infowindow = new kakao.maps.InfoWindow({
                                    content: '<div style="width:150px;text-align:center;padding:6px 0;">{{ rest.rest_name }}</div>'
                                });
                                infowindow.open(map, marker);

                                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                                map.setCenter(coords);
                            }
                        });    
                    </script>

                    {% comment %} <div>조회수 : {{ rest.rest_seenum }}</div> {% endcomment %}
                    {% comment %} <div>추천 : {{ rest.rmd }}</div> {% endcomment %}
                    <div>업데이트날짜 : {{ rest.rest_update }}</div>
                    <br>
                    <br>
                    <div class="container">
                        <h3>리뷰</h3>
                        {% for rev in review %}
                        <p>{{ rev.review_date }}</p>
                        <p><b>{{ rev.review_writer }}</p>
                        <p>{{ rev.review_score }}</p>
                        <p>{{ rev.review_content }}</p>
                        <hr>
                        {% empty %}
                        <p>댓글이 없습니다ㅠㅠ 새로운 댓글을 달아주세요^^</p>
                        {% endfor %}

                        <form method="POST" action="{% url 'restaurant:review' rest.id %}">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <input type="float" class="form-control" placeholder="평점(0.0~5.0)을 입력해주세요" name='score'>
                                <input type="text" class="form-control" placeholder="댓글을 입력해주세요" aria-label="댓글을 입력해주세요"
                                    name='comment'>
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-secondary">등록</button>
                                </div>
                            </div>
                        </form>
                    </div>

                    </section>

                    <!-- 실제 페이지 내용 쓰기 END-->
            </div>
        </div>
    </section>
{% endblock content %}

MINI2/templates/restaurant/restaurant_list.html
{% extends 'mainpage/mainpage.html' %}

{% block content %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option spad set-bg" data-setbg="/static/img/submain-bg.png">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>맛집 게시판</h2>
                        <div class="breadcrumb__links">
                            <a href="/restaurant/">추천맛집리스트</a>
                            <span style="color:mediumaquamarine;">맛집리스트</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- MIDDLE-BOX START -->
    <section class="breadcrumb-option spad set-bg">
        <div class="container">
            <div class="row">
                <!-- 실제 페이지 내용 쓰기 START-->
                <!-- 검색창 시작 -->
                {% include 'restaurant/restaurant_search.html' %}
                <!-- 검색창 끝-->
                <br>
                <br>


                <!-- Blog Section Begin -->
                <section class="blog spad">
                    <div class="container">
                        <div class="row">

                            {% for rest in rest_list %}
                                <div class="col-lg-4 col-md-6 col-sm-6">
                                    <div class="blog__item">
                                        <div class="blog__item__pic">
                                            <a href="/restaurant/{{ rest.id }}">
                                                <img src="{{ rest.rest_img1 | default:'/static/img/dogie.jpg'}}" alt="">
                                            </a>
                                        </div>
                                        <div class="blog__item__text">
                                            <div class="rating">
                                                {% for x in rest.rest_starscore %}
                                                <i class="fa fa-star"></i>
                                                {% endfor %}
                                            </div>
                                            <h5><a href="/restaurant/{{ rest.id }}">{{rest.rest_name}}</a></h5>
                                            <ul>
                                                <li>{{rest.rest_kind}}</li>
                                            </ul>
                                            <h6>{{rest.rest_address}}</h6>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </section>
    <!-- Blog Section End -->
    <!-- 실제 페이지 내용 쓰기 END-->
            </div>
        </div>
    </section>
{% endblock content %}

MINI2/templates/restaurant/restaurant_search.html
{% comment %} 검색한것과 같은 음식점 이름을 가진
restaurant_detail 불러오기
망고플레이트에도 없고 데이터 베이스에도 없으면 검색 없다고 표현 {% endcomment %}
<style>
.footer__newslatter form input::placeholder {
	color: #D3D3D3;
}

.footer__newslatter form input {
	color: #000000;
}
</style>

<div class="col-lg-4 col-md-8">
    <div class="footer__newslatter">
        <form action="/restaurant/restaurant_search/", method="POST">
        {% csrf_token %}
            <input type="text" placeholder="음식점 이름" autocomplete="on" name='search' style="border:1px solid #6B76FF">
            <button type="submit" class="site-btn" style="border:1px solid #6B76FF">검색</button>
        </form>
    </div>
</div>