MINI2/boardapp/urls.py
from django.urls import path, include
from boardapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'boardapp'

urlpatterns = [
    # 자유게시판
    path('freeboard/', views.freeboard, name='freeboard'),
    # 동아리/스터디
    path('studyboard/', views.studyboard, name='studyboard'),
    # 취업/진로
    path('jobboard/', views.jobboard, name='jobboard'),
    # 물물교환/무료나눔
    path('tradeboard/', views.tradeboard, name='tradeboard'),
    path('writetext/', views.writetext, name='writetext'),
    path('<int:pk>/', views.content_view, name='content_view'),
    path('<int:pk>/content_delete/', views.content_delete, name='content_delete'),
    path('comment_write/<int:pk>/', views.comment_write, name='comment_write'),
    path('likes/', views.likes, name="likes"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/calcapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'calcapp'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('donation/', views.donation, name='donation'),
    # 공지사항
    path('notice/', views.notice, name='notice'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('update/<int:blog_id>/', views.update, name='update'),
    path('delete/<int:blog_id>/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('faq/', views.faq, name='faq'),
    path('suggest/', views.suggest, name='suggest'),
    path('qna/', views.qna, name='qna'),

    # 계산기
    path('calcpage/', views.calcpage, name="calcpage"),
    path('calcpage_result/', views.calcpage_result, name="calcpage_result"),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# calcapp/calcpage/

MINI2/config/urls.py
from django.contrib import admin
from django.urls import path, include
import calcapp.views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/', include('mainpage.urls')),
    path('boardapp/', include('boardapp.urls')),
    path('calcapp/', include('calcapp.urls')),
    path('member/', include('member.urls')),
    path('restaurant/', include('restaurant.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.mainhome, name='mainhome'),
]

MINI2/member/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'member'

urlpatterns = [
    path('login/', views.login, name='login'),  
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

    ### 추가된부분 ###
    # 프로필
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/restaurant/urls.py
from django.contrib import admin
from django.urls import path
from restaurant import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.restaurant, name='rest'),
    path('restaurant_list/', views.restaurant_list, name='list'),
    path('<int:pk>/', views.restaurant_detail, name='detail'),
    path('restaurant_review/<int:pk>/', views.restaurant_review, name='review'),
    path('restaurant_search/', views.restaurant_search, name='serach')
    # path('restaurant_search/', views.restaurant_search),
]

MINI2/boardapp/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from member.models import Member
from django.conf import settings

#  모든 자유게시판 게시물 db
class BoardAllContentList(models.Model):
    title = models.CharField(max_length=100)
    # user = models.ForeignKey(Member, on_delete=models.CASCADE) # main user db랑 연결 해야함
    user = models.CharField(max_length=20) # main user db랑 연결 해야함
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    seenum = models.PositiveIntegerField(default=0)
    like = models.ManyToManyField(Member, default=0,related_name='likes') # 좋아요
    # like_count = models.PositiveIntegerField(default=0)
    board_kind = models.CharField(max_length=20)

    def __str__(self):
        return self.title

# # 게시물 별 이미지 db
class Image(models.Model):
    content = models.ForeignKey(BoardAllContentList, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


# 모든 자유게시판 댓글 db
class Board_comment(models.Model):
    content = models.ForeignKey(BoardAllContentList, on_delete=models.CASCADE, null=True, related_name='content')
    comment_date = models.DateTimeField(auto_now_add=True)
    # comment_writer = models.ForeignKey(Member,on_delete=models.CASCADE, null=True)
    comment_writer = models.CharField(max_length=20)
    comment_content = models.TextField(null=True)
    # comment_board_kind = models.CharField(max_length=20)

    def __str__(self):
        return self.title

MINI2/calcapp/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import Blog

class BlogUpdate(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','body', 'images']


# form 이용시 views.py 수정

# from .models import AttendHistroy
# class AttendHistroyFrom(forms.ModelForm):
#     class Meta:
#         model = AttendHistroy
#         fields = '__all__'

MINI2/boardapp/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from .models import BoardAllContentList, Board_comment, Member
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
import json
from django.views.generic import View, ListView, DetailView, FormView, CreateView

# 자유게시판 메인 목록
def freeboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='자유게시판').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################
    context = {
        'list':content_list,
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }
    return render(request, 'boardapp/board_free.html', context)

# 동아리/스터디 메인 목록
def studyboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='동아리/스터디').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }

    return render(request, 'boardapp/board_study.html', context)

# 취업/진로 메인 목록
def jobboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='취업/진로').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }

    return render(request, 'boardapp/board_job.html', context)

# 물물교환/무료나눔 메인 목록
def tradeboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='물물교환/무료나눔').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }
    return render(request, 'boardapp/board_trade.html', context)


# 글쓰기 양식
def writetext(request):
    content = BoardAllContentList()
    # 세션에 로그인 관련 정보 저장
    # 해인
    session_value = request.session['user_name']

    if request.method == 'POST': # 내용 입력후, 전달 할때
        content.title = request.POST['title']
        content.text = request.POST['text']
        content.date = timezone.datetime.now()
        content.user = session_value
        content.board_kind = request.POST['board_kind']
        content.save()

        '''
        for img in request.FILES.getlist('images'):
            # image 객체 생성
            image = Image()
            # 현재 게시물의 기본키 참조
            image.content = content.id
            # images로부터 가져온 이미지파일 하나씩 저장
            image.image = img
            # db에 저장
            image.save()
        '''

        return redirect('/boardapp/' + str(content.pk))
    # 내용 입력 없을 떄
    return render(request, 'boardapp/board_write.html',{})


# 게시글 페이지
def content_view(request, pk):
    content = BoardAllContentList.objects.get(pk=pk)
    content.seenum += 1 # 조회수
    content.save()
    user = Member.objects.all()
    return render(request, 'boardapp/content_view.html', {'content':content})


# 게시글 삭제
def content_delete(request, pk):
    # login_session = request.session.get('login_session','')
    session_user = request.session['user_name']
    print(session_user)
    content = get_object_or_404(BoardAllContentList, pk=pk)
    if content.user == session_user:
        content.delete()
        return redirect('/boardapp/freeboard')
    else:
        return redirect('/boardapp/' + str(content.pk))


# 게시글 댓글
def comment_write(request, pk):
    content = get_object_or_404(BoardAllContentList, pk = pk)
    session_value = request.session['user_name']

    content.content.create(comment_content = request.POST.get('comment'), comment_date = timezone.now(), comment_writer=session_value)
    return redirect('/boardapp/'+str(content.pk))


# 게시글 좋아요
def likes(request):
    # 현재 로그인한 유저
    user = Member.objects.get(user_phone=request.session['user_phone'])

    if request.is_ajax():
        content_id = request.GET['content_id'] # 좋아요 누른 게시물 id
        content = BoardAllContentList.objects.get(id=content_id)
        # print(id)
        like_user_list = content.like.all() # 좋아요 누른 유저 리스트
        print('리스트',like_user_list)

        # 현재 게시물에 좋아요한 사람 중 로그인한사람이 있으면 (이미 좋아요 누른경우이면)
        if user in like_user_list:
            content.like.remove(user) # 현재 로그인한 사람지워
            message ='좋아요취소'
        else:
            content.like.add(user)
            message ='좋아요'

        like_count = content.like.count() # 게시물이 받은 좋아요수
        context={'like_count':like_count, 'message':message}

    return HttpResponse(json.dumps(context), content_type='application/json')

MINI2/mainpage/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from calcapp.models import Blog
from restaurant.models import Rest
from boardapp.models import BoardAllContentList

# Create your views here.
def mainhome(request):
    get_user_phone = request.session.get('user_phone')
    # get_user_phone = request.session['user_phone']
    blogs = Blog.objects.all()
    rest = Rest.objects.all()

    boards = BoardAllContentList.objects.all()

    context = {
        'get_user_phone':get_user_phone,
        'blogs': blogs,
        'rest':rest,
        'boards':boards,
    }

    return render(request, 'mainpage/mainhome.html', context)

MINI2/member/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils import timezone
from django.contrib import messages

from .models import Member
# redierct - url을 이동. name으로 접근. render처럼 context값을 넘기지는 못함.
# render - 화면에 html파일을 띄우기때문에 url이안변함. context값 넘길 수 있음.
# reverse - 

# Create your views here.
def register(request):
    if request.method == 'GET':
        return render(request, 'member/register.html')
     #"POST"
    else: 
        # HTML로부터 받은 정보 확인
        user_name = request.POST['user_name']
        user_pw = request.POST['user_pw']
        user_pwchk = request.POST['user_pwchk']
        user_phone = request.POST['user_phone']

        message_dict = {} # html에 던져줄 dictionary
        
        m = Member(
            user_name = user_name, user_pw=user_pw,
            user_phone = user_phone)
        m.c_date = timezone.now()
        m.save()
        messages.warning(request, '회원가입 성공')
        return redirect('member:register') # urls.py/view-name을 적어야함

def login(request):
    if request.method == 'GET':
        return render(request, 'member/register.html', {})
     # POST
    else:
        # 받은 정보 확인
        u_id = request.POST['user_phone']
        u_pw = request.POST['user_pw']
        
        try:
            m = Member.objects.get(user_phone=u_id)
        
        except:
            return HttpResponse('등록된 회원이 없습니다.')
        else:
            if m.user_pw != u_pw:
                error_messages = '로그인 실패'   
                return render(request, 'member/register.html', 
                        {'error_messages':error_messages})
            else:
                error_messages = ''
                request.session['user_phone'] = u_id
                request.session['user_name'] = m.user_name
                return redirect('mainpage:mainhome')

def logout(request):
    if request.session['user_phone']:
        del request.session['user_phone']
        del request.session['user_name']
        return redirect('mainpage:mainhome')

MINI2/templates/mainpage/footer-box.html
{% load static %}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=8deb5ae77ef38486d8a2541c58a9a934&libraries=services"></script>

<div class="footer">
    <div class="footer__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <div class="footer__logo">
                        <a href="{% url 'mainpage:mainhome' %}" style="color:white; font-size:20px;">Developer Dream</a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="footer__newslatter">
                        <form action="#">
                            <input type="text" placeholder="enter your e-mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h5>Contact</h5>
                    <ul>
                        <li><a href="{% url 'calcapp:contact' %}">Dev Team</a></li>
                        <li><a href="{% url 'calcapp:qna' %}">Q&A</a></li>
                        <li><a href="{% url 'calcapp:faq' %}">FAQ</a></li>
                        <li><a href="{% url 'calcapp:notice' %}">공지사항</a></li>
                        <li><a href="{% url 'calcapp:suggest' %}">건의사항</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h5>Quick links</h5>
                    <ul>
                        <li><a href="{% url 'boardapp:freeboard' %}">자유게시판</a></li>
                        <li><a href="{% url 'boardapp:freeboard' %}">공모전/스터디</a></li>
                        <li><a href="{% url 'boardapp:freeboard' %}">취업/진로</a></li>
                        <li><a href="{% url 'boardapp:freeboard' %}">물물교환/무료나눔</a></li>
                        <li><a href="{% url 'restaurant:rest' %}">가디맛집</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="footer__address">
                    <h5>Our base</h5>
                    <ul>
                        <li><i class="fa fa-map-marker"></i> 서울특별시 금천구 가산디지털1로 168 우림라이온스밸리 A동 620호</li>
                        <li><i class="fa fa-phone"></i> 010-4452-6883</li>
                        <li><i class="fa fa-envelope"></i> hyunicho62@gmail.com</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-6">
                <div id="map" style="width:400px;height:250px;"></div>
                    <script>
                    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
                        mapOption = {
                            center: new kakao.maps.LatLng(37.479966429878, 126.88263620024), // 지도의 중심좌표
                            level: 3 // 지도의 확대 레벨
                        };

                    var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

                    // 마커가 표시될 위치입니다
                    var markerPosition  = new kakao.maps.LatLng(37.479966429878, 126.88263620024);

                    // 마커를 생성합니다
                    var marker = new kakao.maps.Marker({
                        position: markerPosition
                    });

                    // 마커가 지도 위에 표시되도록 설정합니다
                    marker.setMap(map);
                    </script>
            </div>
        </div>
    </div>
    <div class="footer__copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <div class="footer__copyright__text">
                        <p>Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                    </div>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
                <div class="col-lg-5">
                    <ul>
                        <li>All Rights Reserved</li>
                        <li>Terms & Use</li>
                        <li>Privacy Policy</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

MINI2/templates/mainpage/header-box.html
<div class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <ul class="header__top__left">
                        {% comment %} <li><i class="fa fa-phone"></i>1234-5678</li> {% endcomment %}
                        <li><i class="fa fa-map-marker"></i>Seoul, Woorim Lions Valley, Building a, 6th floor A-6</li>
                        {% comment %} <li><i class="fa fa-clock-o"></i>Mon to Sat 9:00am to 18:00pm</li> {% endcomment %}
                    </ul>
                </div>
                <div class="col-lg-4">
                    <div class="header__top__right">
                        <a href="https://github.com/haeinyy/webproject_communitysite"><i class="fa fa-dribbble"></i></a>
                        <a href="{% url 'member:login' %}" id="header-box-login__btn">로그인<i class="fas fa-sign-in-alt"></i></a>
                        <a href="{% url 'member:register' %}" id="header-box-register__btn">회원가입<i class="fas fa-sign-up-alt"></i></a>
                        <a href="{% url 'member:logout' %}" id="header-box-logout__btn">로그아웃<i class="fas fa-sign-out-alt"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
    .header__logo {
        padding: 15px;
    }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="{% url 'mainpage:mainhome' %}">
                        <img src='/static/img/log.png' width="100" height="auto" style="float: none; margin:0 auto;">
                    </a>
                </div>
            </div>
            <div class="col-lg-10">
                <div class="header__menu__option">
                    <nav class="header__menu">
                        <ul>
                            <li><a href="{% url 'calcapp:calcpage_result' %}" id="ajax_button">마이페이지</a>
                            <!-- <li><a href="#" onclick="session_ischeck();">마이페이지</a> -->
                                <ul class="dropdown">
                                    <li><a href="{% url 'calcapp:calcpage_result' %}">계산기</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'boardapp:freeboard' %}">게시판</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'boardapp:freeboard' %}">자유게시판</a></li>
                                    <li><a href="{% url 'boardapp:studyboard' %}">공모전/스터디</a></li>
                                    <li><a href="{% url 'boardapp:jobboard' %}">취업/진로</a></li>
                                    <li><a href="{% url 'boardapp:tradeboard' %}">물물교환/무료나눔</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'restaurant:rest' %}">가디맛집</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'restaurant:rest' %}">추천별</a></li>
                                    <li><a href="{% url 'restaurant:list' %}">리스트</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'calcapp:notice' %}">정보마당</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'calcapp:notice' %}">공지사항</a></li>
                                    <li><a href="{% url 'calcapp:faq' %}">FAQ</a></li>
                                    <li><a href="{% url 'calcapp:suggest' %}">건의사항</a></li>
                                    <li><a href="{% url 'calcapp:qna' %}">Q&A</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'calcapp:contact' %}">Dev Team</a></li>
                        </ul>
                    </nav>
                    <div class="header__btn">
                        <a href="{% url 'calcapp:donation' %}" class="primary-btn">후원</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="canvas__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</div>
<div class="header-box-fill-white">

</div>

MINI2/templates/mainpage/js-script.html
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.magnific-popup.min.js"></script>
<script src="/static/js/masonry.pkgd.min.js"></script>
<script src="/static/js/jquery-ui.min.js"></script>
<script src="/static/js/jquery.nice-select.min.js"></script>
<script src="/static/js/jquery.slicknav.js"></script>
<script src="/static/js/owl.carousel.min.js"></script>
<script src="/static/js/main.js"></script>
<script src="/static/js/header-box-div__show__hide.js"></script>
<!-- {% load static %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script> -->