MINI2/boardapp/urls.py
from django.urls import path, include
from boardapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'boardapp'

urlpatterns = [
    # 자유게시판
    path('freeboard/', views.freeboard, name='freeboard'),
    # 동아리/스터디
    path('studyboard/', views.studyboard, name='studyboard'),
    # 취업/진로
    path('jobboard/', views.jobboard, name='jobboard'),
    # 물물교환/무료나눔
    path('tradeboard/', views.tradeboard, name='tradeboard'),
    path('writetext/', views.writetext, name='writetext'),
    path('<int:pk>/', views.content_view, name='content_view'),
    path('<int:pk>/content_delete/', views.content_delete, name='content_delete'),
    path('comment_write/<int:pk>/', views.comment_write, name='comment_write'),
    path('likes/', views.likes, name="likes"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/calcapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'calcapp'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('donation/', views.donation, name='donation'),
    # 공지사항
    path('notice/', views.notice, name='notice'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('update/<int:blog_id>/', views.update, name='update'),
    path('delete/<int:blog_id>/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('faq/', views.faq, name='faq'),
    path('suggest/', views.suggest, name='suggest'),
    path('qna/', views.qna, name='qna'),

    # 계산기
    path('calcpage/', views.calcpage, name="calcpage"),
    path('calcpage_result/', views.calcpage_result, name="calcpage_result"),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# calcapp/calcpage/

MINI2/config/urls.py
from django.contrib import admin
from django.urls import path, include
import calcapp.views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/', include('mainpage.urls')),
    path('boardapp/', include('boardapp.urls')),
    path('calcapp/', include('calcapp.urls')),
    path('member/', include('member.urls')),
    path('restaurant/', include('restaurant.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/member/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'member'

urlpatterns = [
    path('login/', views.login, name='login'),  
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

    ### 추가된부분 ###
    # 프로필
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MINI2/boardapp/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from member.models import Member
from django.conf import settings

#  모든 자유게시판 게시물 db
class BoardAllContentList(models.Model):
    title = models.CharField(max_length=100)
    # user = models.ForeignKey(Member, on_delete=models.CASCADE) # main user db랑 연결 해야함
    user = models.CharField(max_length=20) # main user db랑 연결 해야함
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    seenum = models.PositiveIntegerField(default=0)
    like = models.ManyToManyField(Member, default=0,related_name='likes') # 좋아요
    # like_count = models.PositiveIntegerField(default=0)
    board_kind = models.CharField(max_length=20)

    def __str__(self):
        return self.title

# # 게시물 별 이미지 db
class Image(models.Model):
    content = models.ForeignKey(BoardAllContentList, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


# 모든 자유게시판 댓글 db
class Board_comment(models.Model):
    content = models.ForeignKey(BoardAllContentList, on_delete=models.CASCADE, null=True, related_name='content')
    comment_date = models.DateTimeField(auto_now_add=True)
    # comment_writer = models.ForeignKey(Member,on_delete=models.CASCADE, null=True)
    comment_writer = models.CharField(max_length=20)
    comment_content = models.TextField(null=True)
    # comment_board_kind = models.CharField(max_length=20)

    def __str__(self):
        return self.title

MINI2/calcapp/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import Blog

class BlogUpdate(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','body', 'images']


# form 이용시 views.py 수정

# from .models import AttendHistroy
# class AttendHistroyFrom(forms.ModelForm):
#     class Meta:
#         model = AttendHistroy
#         fields = '__all__'

MINI2/boardapp/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from .models import BoardAllContentList, Board_comment, Member
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
import json
from django.views.generic import View, ListView, DetailView, FormView, CreateView

# 자유게시판 메인 목록
def freeboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='자유게시판').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################
    context = {
        'list':content_list,
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }
    return render(request, 'boardapp/board_free.html', context)

# 동아리/스터디 메인 목록
def studyboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='동아리/스터디').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }

    return render(request, 'boardapp/board_study.html', context)

# 취업/진로 메인 목록
def jobboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='취업/진로').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }

    return render(request, 'boardapp/board_job.html', context)

# 물물교환/무료나눔 메인 목록
def tradeboard(request):
    content_list = BoardAllContentList.objects.filter(board_kind='물물교환/무료나눔').order_by('-id')

    #################### 검색 ########################
    serach_key = request.GET.get('search_key')
    search_type = request.GET.get('type')
    if serach_key:
        if search_type == 'all':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'title':
            content_list = content_list.filter(title__icontains=serach_key)
        elif search_type == 'text':
            content_list = content_list.filter(text__icontains=serach_key)
        elif search_type == 'writer':
            content_list = content_list.filter(user__icontains=serach_key)
        else:
            messages.error(request, '검색어는 2글자 이상 입력해주세요.')

    ####################################################

    ################### 페이지 번호 ####################
    p = Paginator(content_list,10)
    page = request.GET.get('page')

    if not page:
        page = 1

    info = p.get_page(page)

    # 시작페이지
    start_page = (int(page)-1) // 10 * 10 +1
    end_page = start_page + 9

    # 현재페이지
    now_page = info.number
    # print(now_page)

    if end_page > p.num_pages:
        end_page = p.num_pages
    ####################################################

    context = {
        'content_list':info,
        'pagination' : range(start_page,end_page+1),
        'end_page' : end_page,
        'now_page' : now_page,
    }
    return render(request, 'boardapp/board_trade.html', context)


# 글쓰기 양식
def writetext(request):
    content = BoardAllContentList()
    # 세션에 로그인 관련 정보 저장
    # 해인
    session_value = request.session['user_name']

    if request.method == 'POST': # 내용 입력후, 전달 할때
        content.title = request.POST['title']
        content.text = request.POST['text']
        content.date = timezone.datetime.now()
        content.user = session_value
        content.board_kind = request.POST['board_kind']
        content.save()

        '''
        for img in request.FILES.getlist('images'):
            # image 객체 생성
            image = Image()
            # 현재 게시물의 기본키 참조
            image.content = content.id
            # images로부터 가져온 이미지파일 하나씩 저장
            image.image = img
            # db에 저장
            image.save()
        '''

        return redirect('/boardapp/' + str(content.pk))
    # 내용 입력 없을 떄
    return render(request, 'boardapp/board_write.html',{})


# 게시글 페이지
def content_view(request, pk):
    content = BoardAllContentList.objects.get(pk=pk)
    content.seenum += 1 # 조회수
    content.save()
    user = Member.objects.all()
    return render(request, 'boardapp/content_view.html', {'content':content})


# 게시글 삭제
def content_delete(request, pk):
    # login_session = request.session.get('login_session','')
    session_user = request.session['user_name']
    print(session_user)
    content = get_object_or_404(BoardAllContentList, pk=pk)
    if content.user == session_user:
        content.delete()
        return redirect('/boardapp/freeboard')
    else:
        return redirect('/boardapp/' + str(content.pk))


# 게시글 댓글
def comment_write(request, pk):
    content = get_object_or_404(BoardAllContentList, pk = pk)
    session_value = request.session['user_name']

    content.content.create(comment_content = request.POST.get('comment'), comment_date = timezone.now(), comment_writer=session_value)
    return redirect('/boardapp/'+str(content.pk))


# 게시글 좋아요
def likes(request):
    # 현재 로그인한 유저
    user = Member.objects.get(user_phone=request.session['user_phone'])

    if request.is_ajax():
        content_id = request.GET['content_id'] # 좋아요 누른 게시물 id
        content = BoardAllContentList.objects.get(id=content_id)
        # print(id)
        like_user_list = content.like.all() # 좋아요 누른 유저 리스트
        print('리스트',like_user_list)

        # 현재 게시물에 좋아요한 사람 중 로그인한사람이 있으면 (이미 좋아요 누른경우이면)
        if user in like_user_list:
            content.like.remove(user) # 현재 로그인한 사람지워
            message ='좋아요취소'
        else:
            content.like.add(user)
            message ='좋아요'

        like_count = content.like.count() # 게시물이 받은 좋아요수
        context={'like_count':like_count, 'message':message}

    return HttpResponse(json.dumps(context), content_type='application/json')

MINI2/mainpage/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from calcapp.models import Blog
from restaurant.models import Rest
from boardapp.models import BoardAllContentList

# Create your views here.
def mainhome(request):
    get_user_phone = request.session.get('user_phone')
    # get_user_phone = request.session['user_phone']
    blogs = Blog.objects.all()
    rest = Rest.objects.all()

    boards = BoardAllContentList.objects.all()

    context = {
        'get_user_phone':get_user_phone,
        'blogs': blogs,
        'rest':rest,
        'boards':boards,
    }

    return render(request, 'mainpage/mainhome.html', context)

MINI2/member/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils import timezone
from django.contrib import messages

from .models import Member
# redierct - url을 이동. name으로 접근. render처럼 context값을 넘기지는 못함.
# render - 화면에 html파일을 띄우기때문에 url이안변함. context값 넘길 수 있음.
# reverse - 

# Create your views here.
def register(request):
    if request.method == 'GET':
        return render(request, 'member/register.html')
     #"POST"
    else: 
        # HTML로부터 받은 정보 확인
        user_name = request.POST['user_name']
        user_pw = request.POST['user_pw']
        user_pwchk = request.POST['user_pwchk']
        user_phone = request.POST['user_phone']

        message_dict = {} # html에 던져줄 dictionary
        
        m = Member(
            user_name = user_name, user_pw=user_pw,
            user_phone = user_phone)
        m.c_date = timezone.now()
        m.save()
        messages.warning(request, '회원가입 성공')
        return redirect('member:register') # urls.py/view-name을 적어야함

def login(request):
    if request.method == 'GET':
        return render(request, 'member/register.html', {})
     # POST
    else:
        # 받은 정보 확인
        u_id = request.POST['user_phone']
        u_pw = request.POST['user_pw']
        
        try:
            m = Member.objects.get(user_phone=u_id)
        
        except:
            return HttpResponse('등록된 회원이 없습니다.')
        else:
            if m.user_pw != u_pw:
                error_messages = '로그인 실패'   
                return render(request, 'member/register.html', 
                        {'error_messages':error_messages})
            else:
                error_messages = ''
                request.session['user_phone'] = u_id
                request.session['user_name'] = m.user_name
                return redirect('mainpage:mainhome')

def logout(request):
    if request.session['user_phone']:
        del request.session['user_phone']
        del request.session['user_name']
        return redirect('mainpage:mainhome')

MINI2/templates/boardapp/board_free.html
{% extends 'mainpage/mainpage.html' %}

{% block content %}

<!-- 해인수정 - 페이지경로 -->
<!-- 위에 그림 및 페이지 경로 Url -->
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option spad set-bg" data-setbg="/static/img/submain-bg.png">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>자유게시판</h2>
                    <div class="breadcrumb__links">
                        <a href="/mainpage/">Home</a>
                        <a href="#">게시판</a>
                        <span style="color:mediumaquamarine;">자유게시판</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- MIDDLE-BOX START -->
<section class="breadcrumb-option spad set-bg" data-setbg="">
    <div class="container">
        <!-- 게시물 목록 리스트 / 페이지 번호-->
        <div class="container">
            <!-- 목록 -->
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">번호</th>
                        <th scope="col">제목</th>
                        <th scope="col">작성자</th>
                        <th scope="col">작성일</th>
                        <th scope="col">조회</th>
                        <th scope="col">좋아요</th>
                    </tr>
                </thead>
                <tbody>
                    {% for list in content_list %}
                    <tr>
                        <th scope="row">{{ list.id }}</th>
                        <td><a href="{% url 'boardapp:content_view' list.pk %}">{{ list.title }}</a></td>
                        <td>{{ list.user }}</td>
                        <td>{{ list.date }}</td>
                        <td>{{ list.seenum }}</td>
                        <td>{{ list.like.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- 글쓰기 버튼 -->
            <br>
            <a href="{% url 'boardapp:writetext' %}"><button type="submit"
                    class="btn btn-secondary pull-right">글쓰기</button></a>
            <br><br>

            <!-- 페이지번호 -->
            {% include 'boardapp/pagination.html' %}
            <hr>
        </div>
        <!-- 게시물 목록 리스트 / 페이지번호 끝 -->
        <style>
            .nice-select {
                float: right;
            }
        </style>
        <!-- 게시물검색 -->
        <form action="" method='GET'>
            <div class="container" id="">
                <div class="row justify-content-md-center">
                    <div class="col" id="board-free-bottom__btn">
                        <select name='type'>
                            <option value="all">전체</option>
                            <option value="title">제목</option>
                            <option value="text">내용</option>
                            <option value="writer">작성자</option>
                        </select>
                    </div>
                    <div class="col">
                        <input type="text" name="search_key" value="{{ search_key }}" class="form-control"
                            placeholder="검색어를 입력해주세요">
                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-secondary">검색</button>
                    </div>
                </div>
            </div>
        </form>

        <!-- 실제 페이지 내용 쓰기 END-->
    </div>
</section>
<!-- MIDDLE-BOX END -->


<!-- 밑에 이미지 애니메이션 -->
<!-- Testimonials Section Begin -->
<section class="testimonials spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="section-title">
                    <span>실시간급상승</span>
                    <h2>Today's HOT</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="testimonial__slider owl-carousel">
                <div class="col-lg-6">
                    <div class="testimonial__item">
                        <div class="testimonial__author">
                            <div class="testimonial__author__icon">
                                <i class="fa fa-quote-left"></i>
                            </div>
                            <div class="testimonial__author__text">
                                <h5>Catanis Greimar</h5>
                                <span>Businesswoman</span>
                            </div>
                        </div>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <p>Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas
                            accumsan lacus
                            vel facilisis ut labore et dolore magna aliqua accumsan lacus vel facilisis.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="testimonial__item">
                        <div class="testimonial__author">
                            <div class="testimonial__author__icon">
                                <i class="fa fa-quote-left"></i>
                            </div>
                            <div class="testimonial__author__text">
                                <h5>Catanis Greimar</h5>
                                <span>Businesswoman</span>
                            </div>
                        </div>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <p>Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas
                            accumsan lacus
                            vel facilisis ut labore et dolore magna aliqua accumsan lacus vel facilisis.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="testimonial__item">
                        <div class="testimonial__author">
                            <div class="testimonial__author__icon">
                                <i class="fa fa-quote-left"></i>
                            </div>
                            <div class="testimonial__author__text">
                                <h5>Catanis Greimar</h5>
                                <span>Businesswoman</span>
                            </div>
                        </div>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <p>Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas
                            accumsan lacus
                            vel facilisis ut labore et dolore magna aliqua accumsan lacus vel facilisis.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="testimonial__item">
                        <div class="testimonial__author">
                            <div class="testimonial__author__icon">
                                <i class="fa fa-quote-left"></i>
                            </div>
                            <div class="testimonial__author__text">
                                <h5>Catanis Greimar</h5>
                                <span>Businesswoman</span>
                            </div>
                        </div>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <p>Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas
                            accumsan lacus
                            vel facilisis ut labore et dolore magna aliqua accumsan lacus vel facilisis.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="testimonial__item">
                        <div class="testimonial__author">
                            <div class="testimonial__author__icon">
                                <i class="fa fa-quote-left"></i>
                            </div>
                            <div class="testimonial__author__text">
                                <h5>Catanis Greimar</h5>
                                <span>Businesswoman</span>
                            </div>
                        </div>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <p>Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas
                            accumsan lacus
                            vel facilisis ut labore et dolore magna aliqua accumsan lacus vel facilisis.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="testimonial__item">
                        <div class="testimonial__author">
                            <div class="testimonial__author__icon">
                                <i class="fa fa-quote-left"></i>
                            </div>
                            <div class="testimonial__author__text">
                                <h5>Catanis Greimar</h5>
                                <span>Businesswoman</span>
                            </div>
                        </div>
                        <div class="rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <p>Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas
                            accumsan lacus
                            vel facilisis ut labore et dolore magna aliqua accumsan lacus vel facilisis.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Testimonials Section End -->

{% endblock content %}

MINI2/templates/boardapp/pagination.html
<ul class="pagination justify-content-center">
    <!-- 첫페이지로 -->
    <li class='page-item'><a class = 'page-link' href="?page=1" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
    </a></li>

    <!-- 이전 페이지 묶음 -->
    {% if content_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ content_list.previous_page_number }}">
            Previous
        </a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">Previous</a>
    </li>
    {% endif %}

    <!-- 페이지숫자 -->
    {% for i in content_list.paginator.page_range %}
        {% if i == content_list.number %}
        <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{i}}</a>
            </li>
        <li>
        {% else %}
        <li class="page-item" aria-current="page">
            <a class="page-link" href="/boardapp/freeboard/?page={{i}}">{{i}}</a>
        </li>
        {% endif %}
    {% endfor %}

    <!-- 다음 페이지 묶음 -->
    {% if content_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ content_list.next_page_number }}" aria-label="Next">
            Next
        </a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
    </li>
    {% endif %}

    <!-- 마지막페이지로 -->
    <li class='page-item'><a class = 'page-link' href="?page={{end_page}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
    </a></li>
</div>
</ul>

MINI2/templates/boardapp/upload.html
<form action="/upload1/" method="post" enctype="multipart/form-data">
    <input type="file" name="my_file">
    <input type="submit" value="완료">
    {% csrf_token %}
</form>